### ISSUE TITLE
Exception occured

### ISSUE THREAD

**Issue by Leviathan09** [yunity/fritzinfluxdb#11]
Hi, i'm not sure if this is a problem of fritzinfluxdb or fritzconnect, mayber you can help me
Getting the following output when execute ./fritzinfluxdb.py

`INFO: Done parsing config file
INFO: Connection to InfluxDB established and database present
INFO: Successfully connected to FritzBox
Traceback (most recent call last):
  File "/home/collector/environments/fritzinfluxdb/.venv/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 123, in raise_fritzconnection_error
    root = etree.fromstring(response.content)
  File "/usr/lib/python3.7/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 156

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./fritzinfluxdb.py", line 200, in <module>
    main()
  File "./fritzinfluxdb.py", line 182, in main
    points = query_points(fritz_client_unauth, unauth_services)
  File "./fritzinfluxdb.py", line 60, in query_points
    this_result = fc.call_action(service, action)
  File "/home/collector/environments/fritzinfluxdb/.venv/lib/python3.7/site-packages/fritzconnection/core/fritzconnection.py", line 218, in call_action
    return self.soaper.execute(service, action_name, arguments)
  File "/home/collector/environments/fritzinfluxdb/.venv/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 233, in execute
    return handle_response(response)
  File "/home/collector/environments/fritzinfluxdb/.venv/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 218, in handle_response
    raise_fritzconnection_error(response)
  File "/home/collector/environments/fritzinfluxdb/.venv/lib/python3.7/site-packages/fritzconnection/core/soaper.py", line 133, in raise_fritzconnection_error
    raise FritzConnectionException(msg)
fritzconnection.core.exceptions.FritzConnectionException: Unable to perform operation. 401 Unauthorized (ERR_NONE)401 UnauthorizedERR_NONEWebserver Mon, 03 Aug 2020 06:47:12 GMT`

**Comment by bb-Ricardo** [comment]
Hi,

Can you please try the "next-release" branch?

**Comment by Leviathan09** [comment]
Made a complete new installation according to your guide
Now i get this:

`(.venv) collector@test-server:/opt/fritzinfluxdb$ ./fritzinfluxdb.py`
`2020-08-03 07:31:31,869 - INFO: Done parsing config file`
`2020-08-03 07:31:31,874 - INFO: Connection to InfluxDB established and database present`
`2020-08-03 07:31:33,566 - INFO: Successfully connected to FritzBox`
`2020-08-03 07:31:33,566 - INFO: Starting main loop`
`2020-08-03 07:31:34,189 - ERROR: Requested invalid action: GetInfo`
`2020-08-03 07:31:34,189 - ERROR: Encountered errors while requesting data. Exit`

**Comment by bb-Ricardo** [comment]
interesting, which FritzBox Model are you using. Can you run it in "-v" debug mode?

**Comment by bb-Ricardo** [comment]
and did you update the config?

please use the new config template and copy your login credentials.

The services and actions changed with the library update.

Sorry

**Comment by Leviathan09** [comment]
Edited the config file with my database and fritzbox credentials
I'm using a FritzBox 7590 with 7.20

Attached you the output of running it with "-v"
[output_verbose.txt](https://github.com/yunity/fritzinfluxdb/files/5014537/output_verbose.txt)

**Comment by bb-Ricardo** [comment]
You are not using a PPP connection?

I got the same model and FW version.

you could just delete `[service9]` from the config and then it should work.

I have to change this behavior as well.

**Comment by Leviathan09** [comment]
Yes WAN connection itself comes from another device
deleted `[service9]` from config and the error is gone

Everything seems to work properly now

Thank you for your fast help

**Comment by bb-Ricardo** [comment]
Just changed the behavior. You will get an error but the rest of the data is requested and pushed to InfluxDB.


> Yes WAN connection itself comes from another device
> deleted `[service9]` from config and the error is gone
> 
> Everything seems to work properly now

great

> Thank you for your fast help

you're welcome.

**Comment by bb-Ricardo** [comment]
released new v0.3.0 version
