### ISSUE TITLE
more values

### ISSUE THREAD

**Issue by celevra** [yunity/fritzinfluxdb#12]
Hi,

is there a way to get Values like SNR and Failure count and so on?

regards

celevra

**Comment by bb-Ricardo** [comment]
All values should be documented here: https://wiki.fhem.de/w/index.php?title=FRITZBOX

which ones are refering to exactly?

**Comment by celevra** [comment]
all of these:
![image](https://user-images.githubusercontent.com/232437/93514500-91993880-f927-11ea-95d1-65c69851e297.png)

i'm not sure where on the wiki i can find the list of possible values

**Comment by bb-Ricardo** [comment]
Should be in here: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wandslifconfigSCPD.pdf

You would need to add them here in your config: https://github.com/yunity/fritzinfluxdb/blob/671dc3ecd9f17b28c6b3efc9e650fbf13516b97b/fritzinfluxdb.ini-sample#L70

And once they get collected you need to add them to the Grafan Dashboard.

**Comment by celevra** [comment]
awesome! Thank you!
________________________________
Von: Ricardo <notifications@github.com>
Gesendet: Donnerstag, 17. September 2020 21:07
An: yunity/fritzinfluxdb
Cc: Philipp Zeitschel; Author
Betreff: Re: [yunity/fritzinfluxdb] more values (#12)


Should be in here: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wandslifconfigSCPD.pdf

You would need to add them here in your config: https://github.com/yunity/fritzinfluxdb/blob/671dc3ecd9f17b28c6b3efc9e650fbf13516b97b/fritzinfluxdb.ini-sample#L70

And once they get collected you need to add them to the Grafan Dashboard.
