### ISSUE TITLE
Make grafana dashboard datasource configurable

### ISSUE THREAD

**Issue by jbreitbart** [yunity/fritzinfluxdb#14]
I just setup your scripts. Seems to work fine, but it took me longer than I like to admit to connect it to the correct data source in grafana. An option to directly select that would be great.

**Comment by bb-Ricardo** [comment]
Thank you for pointing this out and sorry that it caused you trouble.

I added a newer dashboard version which also supports selecting a source.

Can you try it out?

**Comment by jbreitbart** [comment]
Thanks a lot. That worked like a charm. I still have a few panels without data, but I think the data is missing as I have the fritzbox connected via LAN to a speedport router.

**Comment by bb-Ricardo** [comment]
Great to hear and thanks for testing.

Yes, the DSL panel will probably be empty. But there are also WAN interface statistics. Maybe you can add a service to export the WAN interface stats and these could be used in the panel.

**Comment by jbreitbart** [comment]
Do you know if the daily traffic and last 24h upload/download should be empty if I use the sample ini without service9?

**Comment by ronaldn1969** [comment]
Hi... This have no impact, because daily traffic comes from serive1

**Comment by jbreitbart** [comment]
Ok, then I'll have to look into that a bit more. I am closing this ticket since it is resolved. Thanks for help. :smiley:
