### ISSUE TITLE
not able to start docker file...

### ISSUE THREAD

**Issue by ronaldn1969** [yunity/fritzinfluxdb#16]
Hi Ricardo, hi all

I'm new in Linux and also in Docker and face a problem with the Docker file I created...

First I tried to install your script in the virtual environment on my pc without any problem. Afterwards I tried to use the docker way, because I want to use it on a Raspberry PI in combination with a influx/grafana docker container. This container is running well...

I used the way you described:

ronald@buster:/opt$ **sudo git clone https://github.com/yunity/fritzinfluxdb.git**
Klone nach 'fritzinfluxdb' ...
remote: Enumerating objects: 144, done.
remote: Total 144 (delta 0), reused 0 (delta 0), pack-reused 144
Empfange Objekte: 100% (144/144), 130.37 KiB | 185.00 KiB/s, Fertig.
Löse Unterschiede auf: 100% (80/80), Fertig.
ronald@buster:/opt$ **cd fritzinfluxdb**
ronald@buster:/opt/fritzinfluxdb$ **docker build -t fritzinfluxdb .**
Sending build context to Docker daemon    406kB
:
:
Step 5/5 : CMD [ "python", "./fritzinfluxdb.py" ]
 ---> Running in df9377423fcf
Removing intermediate container df9377423fcf
 ---> c7f51a4cec46
Successfully built c7f51a4cec46
Successfully tagged fritzinfluxdb:latest

Then I modified the fritzinfluxdb.ini and saved it in my home directory... I have two copies... fritzinfluxdb.ini and my-fritzinfluxdb.ini

If I now start the container with

ronald@buster:/opt/fritzinfluxdb$ **docker run -d -v /home/ronald/fritzbox/my-fritzinfluxdb.ini:/app/idefault.ini --name fritzinfluxdb fritzinfluxdb** or
ronald@buster:/opt/fritzinfluxdb$ **docker run -d -v /home/ronald/fritzbox/fritzinfluxdb.ini:/app/idefault.ini --name fritzinfluxdb fritzinfluxdb**

and then take a look into the logs, I get this message:

ronald@buster:/opt/fritzinfluxdb$ docker container logs --details fritzinfluxdb
 2021-01-13 08:14:29,435 - ERROR: Config file "./fritzinfluxdb.ini" not found

Even with my-fritzinfluxdb.ini or fritzinfluxdb.ini

The only thing, what happen is, that I got two folder (my-fritzinfluxdb.ini or fritzinfluxdb.ini) in /home/ronald/fritzbox

Now is the question, what I have to change, that I get it running... Hope you or someone have a clue or idea what I have to do...

Thanks a lot in advanced
Ronald

**Comment by bb-Ricardo** [comment]
Hi,

you need to change the config (fritzinfluxdb.ini) **BEFORE** running `docker build`.

can you try that?

**Comment by ronaldn1969** [comment]
Hi

Yes... now it's running... ;o)

Connected to Fritzbox, but I have to check my influx database, get "ERROR: Problem connecting to database: HTTPConnectionPool(host='127.0.0.1', port=8086): Max retries exceeded with url: /query?q=SHOW+DATABASE&db=fritzbox (Caused by NewConnectionError('<urllib3.connection.TTPConnection object at 0x7f8c02550d30>: Failed to establish a new connection: [Errno 111] Connection refused',))

Thanks for your quick response!!
Ronald

**Comment by bb-Ricardo** [comment]
You need to know which port influxdb exposes to the host.
you could test on your machine if `curl http://127.0.0.1:8086` works and inxluxdb responds. If not then you need to find the correct influx port.

**Comment by ronaldn1969** [comment]
i don't know... with curl i get "404 page not found"

if I run influx I get the the message: Connected to http://localhost:8086 version 1.8.3

and it looks like that influx is listening on :8088 and 8086

 ss -lntu
Netid              State               Recv-Q              Send-Q                           Local Address:Port                            Peer Address:Port             
tcp                LISTEN              0                   128                                  127.0.0.1:8088                                 0.0.0.0:*                
tcp                LISTEN              0                   128                                    0.0.0.0:22                                   0.0.0.0:*                
tcp                LISTEN              0                   128                                          *:3000                                       *:*                
tcp                LISTEN              0                   50                                           *:1716                                       *:*                
tcp                LISTEN              0                   128                                          *:8086                                       *:*                
tcp                LISTEN              0                   128                                       [::]:22                                      [::]:* 

In grafana I also use http://localhost:8086 without getting trouble.

**Comment by bb-Ricardo** [comment]
Sorry for not getting back.

can you try to add `--network host` to the docker run command?

**Comment by ronaldn1969** [comment]
thanks for still helping me... ;o)

I tried again with... --network 127.0.0.1, --network localhost and --network 192.168.178.20...

everytime i get: docker: Error response from daemon: network xxxxxxxx not found.

I don't know whats wrong with my installation...

cheers
ronald

**Comment by ronaldn1969** [comment]
it's running... but I don't know, why...

All changes I made was not successful. so I modified the username in section [fritzbox] to check if I will get a error message because of wrong username and started the container with **docker run -d -v /usr/share/fritzbox/fritzinfluxdb.ini:/app/idefault.ini --name fritzinfluxdb fritzinfluxdb** as written in your description... but nothing happend... still connected to my fritzbox...

Then I change the running command to docker run -d -v /usr/share/fritzbox/fritzinfluxdb.ini:/**app/fritzinfluxdb.ini** --name fritzinfluxdb fritzinfluxdb still with the wrong parameter... but

pi@raspberrypi:/usr/share/fritzbox $ docker logs fritzinfluxdb --details                                                 
 2021-01-18 20:02:39,850 - INFO: Done parsing config file
 2021-01-18 20:02:39,864 - INFO: Connection to InfluxDB established and database present
 2021-01-18 20:02:42,001 - INFO: Successfully connected to FritzBox
 2021-01-18 20:02:42,003 - INFO: Starting main loop

I took a look inside the container... and checked the inside fritzinfluxdb.ini. It contains the wrong username, but it's running and I also get the informations in grafana...

Could you explain, why it's now running, even with a wrong fritzbox username? 

And if I want to change the settings for collected data, how can I do this, because it looks like that the program didn't ready the overwritten fritzinfluxdb.ini. Do I have to build a new image with the modified ini file?

thanks a lot for your support...

Cheers 
Ronald

**Comment by ronaldn1969** [comment]
Because it's now running, and I know why, I will close this issue... thanks for your patience and support...

**Comment by bb-Ricardo** [comment]
Hey,

I got some time to test around and figured out why it wasn't working for you.

Yes, the instructions about the docker run command was wrong. Fixed it.

can you check this part of the docs if this works for you?: https://github.com/yunity/fritzinfluxdb#example

**Comment by ronaldn1969** [comment]
Hi Ricardo

Thanks for taking a look... I made it as written in "example" and it is running well... 

But I think you have some typos... you wrote my-fr**TI**zinfluxdb.ini and /PATH/TO/my-fr**TI**zinfluxdb.ini:/app/fr**TI**zinfluxdb.ini

The otherway to get the connection to the influxdb ist to write the IP address from the InfluxDB Host inside the fritzinfluxdb.ini. In my case the IP address from my RasPI.

Anyway, now it's running and I appreciate your work and support...!!!

Cheers
Ronald

**Comment by bb-Ricardo** [comment]
> Hi Ricardo
> 
> Thanks for taking a look... I made it as written in "example" and it is running well...
> 
> But I think you have some typos... you wrote my-fr**TI**zinfluxdb.ini and /PATH/TO/my-fr**TI**zinfluxdb.ini:/app/fr**TI**zinfluxdb.ini

THANK YOU. This is embarrassing but fixed now. 

> The otherway to get the connection to the influxdb ist to write the IP address from the InfluxDB Host inside the fritzinfluxdb.ini. In my case the IP address from my RasPI.

This works as well, true. But needs to be the interface IP. With the `--link` option the traffic stays inside the docker bridge network and you don't need to expose the influxdb port if influx is just consumed by other docker containers.

> Anyway, now it's running and I appreciate your work and support...!!!

You're welcome
